### ISSUE TITLE
AZURE  cloud provider improvements

### ISSUE THREAD

**Issue by MalloZup** [SUSE/ha-sap-terraform-deployments#144]
# description:
This card is more a meta-tracker for issue I found in azure. To keep track of them.

I wil refine the card step by step and update it.

# tasks

- [ ] add similar mechanism with `tfvars` like libvirt for having same 1:1 parity. this should be the only was to give inputs. 
- [x] add monitoring
- [ ] Move to modules 
- [ ] improve doc 
- [ ] find better name for this: https://github.com/SUSE/ha-sap-terraform-deployments/blob/master/azure/resources.tf#L6 
- [ ] naming of the resources are bad `myas` ,`myroutes` etc this prefix should be removed

**Comment by MalloZup** [comment]
https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/examples/virtual-machines/2-vms-loadbalancer-lbrules/main.tf

**Comment by MalloZup** [comment]
Add same vars terraform ans grains as libvirt to Make same behaviors

**Comment by MalloZup** [comment]
closing adressed most of it
