### ISSUE TITLE
NEXT-RELEASE 2.2.0

### ISSUE THREAD

**Issue by MalloZup** [SUSE/ha-sap-terraform-deployments#183]
# Description:

Checklist of things need to be done before next release in GitHub.

# Checklist

- [x] fix `output.tf` - useful for openQA tests (https://github.com/SUSE/ha-sap-terraform-deployments/pull/217 and https://github.com/SUSE/ha-sap-terraform-deployments/pull/220)
- [x] add monitoring for GCP (https://github.com/SUSE/ha-sap-terraform-deployments/pull/219)
- [x] add monitoring for AWS (https://github.com/SUSE/ha-sap-terraform-deployments/pull/203)
- [x] have the choice to  disable monitoring on Azure (https://github.com/SUSE/ha-sap-terraform-deployments/issues/182)
- [x] ntpd issue on SLE12+ (https://github.com/SUSE/ha-sap-terraform-deployments/issues/208)
- [x] disable ha_exporter by default (https://github.com/SUSE/ha-sap-terraform-deployments/issues/181)

# Validation

Test runs should passed on all providers with `pillar_examples/automatic/*.sls` files and with default values

Validation with `background = true` (recommended value):
- [x] Azure
- [x] AWS
- [x] GCP
- [x] Libvirt

Validation with `background = false` (default value, and used for automated QA tests with openQA):
- [x] Azure
- [x] AWS
- [x] GCP
- [x] Libvirt

**Comment by ricardobranco777** [comment]
Maybe https://github.com/SUSE/ha-sap-terraform-deployments/issues/97 too?

We supported it before.

**Comment by MalloZup** [comment]
@ricardobranco777 next release 🐧

**Comment by MalloZup** [comment]
Done thx
